# archivo .nginx.conf en la raíz del proyecto
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;  # o tu dominio

        root /var/www/html/public;
        index index.php;

        client_max_body_size 50M;
        gzip on;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/x-javascript application/json application/javascript image/x-icon image/png image/gif image/jpeg image/svg+xml;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass unix:/var/run/php/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Limita acceso a archivos ocultos y entorno
        location ~ /\.(?!well-known).* {
            deny all;
        }

        # Estáticos seguros
        location ~ ^/(favicon\.ico|robots\.txt)$ {
            access_log off;
            log_not_found off;
        }
    }
}
