version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gridded/tastyigniter:latest
    container_name: tastyigniter_app
    ports:
      - "80:80"
    environment:
      APP_NAME: "Beautiful Parrilla"
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "https://beautiful-app.gridded.agency"
      APP_KEY: "" # Generado en el primer arranque si no se define
      TI_THEME: "gridded_agency-orange"

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: default
      DB_USERNAME: root
      DB_PASSWORD: secret

      CACHE_DRIVER: file
      SESSION_DRIVER: file
      LOG_CHANNEL: stderr

    depends_on:
      - db
    volumes:
      - ./themes:/var/www/html/themes
      - ./extensions:/var/www/html/extensions
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    restart: always

  db:
    image: mariadb:10.6
    container_name: tastyigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
