user  www-data;
worker_processes  auto;
pid   /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_disable "msie6";
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen       80;
        server_name  _;

        root   /var/www/html/public;
        index  index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~* ^/(themes|storage|app)/.*\.(?:jpg|jpeg|gif|png|css|js|ico|woff2?|ttf|svg|eot)$ {
            access_log off;
            expires max;
            add_header Cache-Control "public";
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }

        location = /favicon.ico  { access_log off; log_not_found off; }
        location = /robots.txt   { access_log off; log_not_found off; }
    }
}
